# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

desc "Get current tag"
lane :get_current_tag do
  tags = sh('git tag --sort=-creatordate | head -n 1') # Get the latest tag
  if tags.strip.empty?
    UI.user_error!("No git tags found! Please create a tag to start versioning.")
  end
  tags.strip
end

desc "Get commit counts"
lane :get_commits_count do |options|
  current_tag = get_current_tag
  current_commit = last_git_commit[:abbreviated_commit_hash]
  if options[:from_env]
    current_commit = ENV['SEMAPHORE_GIT_SHA']
  end
  git_log = sh("git log --oneline #{current_tag.strip}..#{current_commit.strip}")
  count = git_log.lines.count.to_s
  puts "Number of commits since the last tag: #{count}"
  count
end

desc "Generate new version number"
lane :generate_new_version do
  current_tag = get_current_tag.strip
  total_commit_count = get_commits_count({}).to_i

  # Split the current version from the tag into <major>.<minor>
  major, minor = current_tag.sub('v', '').split('.').map(&:to_i)

  # Increment the minor version and add the patch (commit count)
  new_version = "#{major}.#{minor + 1}.#{total_commit_count}"
  puts "Generated new version: #{new_version}"
  new_version
end

desc "Update version number"
lane :update_version do
  new_version = generate_new_version
  # Update version in your project files (e.g., Info.plist or Gradle)
  increment_version_number(version_number: new_version)
  puts "Version updated to #{new_version}"
end

desc "Get generated build number"
lane :get_current_build_number do |options|
  sha_hex = last_git_commit[:abbreviated_commit_hash]
  build_number = sha_hex.to_i(16) # Convert commit hash to integer as base build number
  puts "Generated build number: #{build_number}"
  build_number
end
